---
kind: service.CodeCov
spec:
  targetThreshold: 30
---
kind: common.Repository
spec:
  license:
    id: BSL-1.1
    params:
      Licensor: Sidero Labs, Inc.
      LicensedWork: Discovery Service
      Copyright: (c) 2021 Sidero Labs, Inc.
      ChangeDate: "2025-10-28"
      ChangeLicense: Mozilla Public License, version 2.0
      EnterpriseLink: https://www.siderolabs.com/contact/
    header: |
      // Copyright (c) 2021 Sidero Labs, Inc.
      //
      // Use of this software is governed by the Business Source License
      // included in the LICENSE file.
